version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: Asia/Ho_Chi_Minh
    ports:
      - "${DB_PORT}:3306"
    env_file:
      - .env
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
      interval: 30s

  backend:
    build:
      context: ./backend_path  # Thay bằng path thực tế
      dockerfile: Dockerfile
    container_name: hardening_backend
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      DB_HOST: mysql
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./backend_path:/app  # Mount để live reload

  frontend:
    build:
      context: ./frontend_path  # Thay bằng path thực tế  
      dockerfile: Dockerfile
    container_name: hardening_frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend

  adminer:
    image: adminer:latest
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql

volumes:
  mysql_data: